### ISSUE TITLE
Keine Werte 

### ISSUE THREAD

**Issue by kitt2011** [KlausLi/EspEpeverController#1]
Tolle Arbeit die du da machst:) ich wollte es gleich ausprobieren aber leide bekomme ich auf meinem mqtt server keine Werte. Habe es mit beiden 485 Modulen probiert. Angeschlossen sind beide richtig, mache gerne nochmal ein Bild.
Ist ein tracer 4210an.

![Screenshot_20211006_185007_io.homeassistant.companion.android.jpg](https://user-images.githubusercontent.com/86961971/136259645-80c79177-e1de-43c9-afcc-ac96aa21cceb.jpg)

Danke dir:)

**Comment by KlausLi** [comment]
Bei mir läuft a und b auf Pin 4 und 5 vom Rj485

**Comment by kitt2011** [comment]
ich wechsel doch auf die 3,3v und habe mich an die beschreibung gehalten. Wieso so ein wenig unhöflich? Ich erbitte doch nur hilfe und sage danke und alles. Muss nicht sein!
Wer weiß ob du TX UND RX andere Pins in deiner Config verwendest? hättest ja auch gpio 2 als TX für den 485 nehmen können, gibt mehrere TX und RX adressen deswegen fragte ich ja nett.

**Comment by KlausLi** [comment]
nur mal zum testen 
nimm nen neuen esp und neues Rs485 Modul und das DE RE Modul mit gpio0 anschluss 
evtl hat was nen knax weg von den 5v die du vorher benutzt hast

**Comment by KlausLi** [comment]
da fruchtloses unterfangen , CLOSED
